version: "3.3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 4000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ./web:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: chata
      MYSQL_ROOT_PASSWORD: chata
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./web:/var/www/html
